### ISSUE TITLE
Invoice redemption() method throwing IndexError: list index out of range

### ISSUE THREAD

**Issue by bhelx** [recurly/recurly-client-python#137]
Reported by @whiteotter 

When calling redemption() on an invoice that is returning an empty <redemptions /> array:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    redemption = invoice.redemption()
  File "/usr/local/lib/python2.7/site-packages/recurly/__init__.py", line 621, in redemption
    return self.redemptions()[0]
IndexError: list index out of range
```

My initial thoughts are that this should be returning None in the case that the array is empty.

May want to check that other overrides of `redemption()` are handling this correctly as well.

**Comment by bhelx** [comment]
I was able to reproduce this. I just took an invoice with no redemptions and called `redemptions()` on it:

```python
invoice = recurly.Invoice.get('1054')
print invoice.redemptions()
```

**Comment by bhelx** [comment]
Was not able to reproduce with current release. Please re-open if it's a problem.
