### ISSUE TITLE
No access to recurly.Transaction optional attribute "transaction_error"?

### ISSUE THREAD

**Issue by cce** [recurly/recurly-client-python#30]
Hi, when we have an unsuccessful transaction, there's this `transaction_error` section described in the Recurly API that [should be in there](http://docs.recurly.com/api/transactions) but we get the "Could not determine resource class" error.  Perhaps like issue #27 the Python client just doesn't have support for this attribute yet?  Let me know if I'm doing something wrong .. thanks!

```
>>> t
<recurly.Transaction object at 0x4c42a90>
>>> t.attributes
('uuid', 'action', 'account', 'currency', 'amount_in_cents', 'tax_in_cents', 'status', 'reference', 'test', 'voidable', 'refundable', 'cvv_result', 'avs_result', 'avs_result_street', 'avs_result_postal', 'created_at', 'details', 'type')
>>> t.status
'declined'
>>> t.transaction_error
Traceback (most recent call last):
  File "/venv/lib/python2.7/site-packages/weberror/evalcontext.py", line 35, in exec_expr
    exec code in self.namespace, self.globs
  File "<web>", line 1, in <module>
  File "/venv/lib/python2.7/site-packages/recurly/resource.py", line 501, in __getattr__
    return self.value_for_element(elem)
  File "/venv/lib/python2.7/site-packages/recurly/resource.py", line 351, in value_for_element
    value_class = cls._subclass_for_nodename(elem.tag)
  File "/venv/lib/python2.7/site-packages/recurly/resource.py", line 300, in _subclass_for_nodename
    % nodename)
ValueError: Could not determine resource class for array member with tag 'transaction_error'
```

**Comment by bhelx** [comment]
@cce @grahamcwill Please re-open if you are still having problems with this. Would be happy to help you figure out a solution.
