### ISSUE TITLE
Get coupon by strange code API error

### ISSUE THREAD

**Issue by zhavir** [recurly/recurly-client-python#456]
**Describe the bug**
If you try to get a coupon by code using this method `recurly.client.Client.get_coupon` with a strange name like `I%20have%20.`. The client will raise a generic error that cannot be handled IMHO.

> [2020-10-15 15:17:52,231 clouda ae5f6eef9b4f django.request 108 140604428265216 unknown unknown unknown ERROR] Internal Server Error: /api/v1/coupons/recurly/I have ./
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/uncle-scrooge/apps/subscriptions/views/api/coupons_api.py", line 46, in retrieve
    coupon = SubscriptionFacade.get_coupon(
  File "/uncle-scrooge/apps/subscriptions/facades/subscription_facade.py", line 650, in get_coupon
    coupon_data = provider_service.get_coupon(coupon_code, plan_code)
  File "/uncle-scrooge/apps/subscriptions/providers/recurly/service.py", line 1331, in get_coupon
    remote_coupon = self._get_remote_coupon(coupon_code)
  File "/uncle-scrooge/apps/subscriptions/providers/recurly/service.py", line 1322, in _get_remote_coupon
    return self._make_client_call(partial(self._client.get_coupon, f'code-{coupon_code}'))
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 293, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 359, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 320, in iter
    return fut.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 362, in call
    result = fn(*args, **kwargs)
  File "/uncle-scrooge/apps/subscriptions/providers/recurly/service.py", line 432, in _make_client_call
    return partial_func()
  File "/usr/local/lib/python3.8/site-packages/recurly/client.py", line 1071, in get_coupon
    return self._make_request("GET", path, None, None)
  File "/usr/local/lib/python3.8/site-packages/recurly/base_client.py", line 47, in _make_request
    raise ApiError(
recurly.ApiError: Unknown Error. Recurly Request Id: 5e2a8267a955cd16-FCO

**Expected behavior**

I will expect that a specific error will be raised and not a generic recurly.ApiError that could hide some other problems.

**Your Environment**

- Which version of this library are you using? 3.5.1
- Which version of the language are you using? python 3.8

**Comment by joannasese** [comment]
Hi @zhavir. Thanks for reporting this. Invalid coupon codes should trigger something more specific than a general ApiError, as you stated. We'll investigate.

**Comment by joannasese** [comment]
Hi @zhavir. This bug was not related to the Python client library, but a fix for this is scheduled to go live on the 30th. I'll keep this issue open until the fix is released.
